### ISSUE TITLE
Roadmap to v3

### ISSUE THREAD

**Issue by DavidGarciaCat** [mailgun/mailgun-php#442]
## API Reference

- [x] Messages
  - [x] Batch Message - PR https://github.com/mailgun/mailgun-php/pull/472
- [x] Domains
- [x] IPs - Issue https://github.com/mailgun/mailgun-php/issues/458
- [x] Events
- [x] Stats
- [x] Tags
  - [x] Retrieve and update Tags
  - [x] Retrieve base Tag stats
  - [x] Retrieve aggregates Tag stats (countries / providers / devices) - Issue https://github.com/mailgun/mailgun-php/issues/453
- [x] Suppressions
- [x] Routes
- [x] Webhooks
- [x] Mailing Lists - Issue https://github.com/mailgun/mailgun-php/issues/456 PR https://github.com/mailgun/mailgun-php/pull/457
- [x] Email Validation - Issue https://github.com/mailgun/mailgun-php/issues/191 PR https://github.com/mailgun/mailgun-php/pull/427
- [ ] ~Email Validation v4 - Issue #617 #619 PR #618~ (will be offered in 3.x)

## ToDo

- [x] Update Assets to validate the limits when available on endpoints - Issue #461 PR #565
- [ ] ~Update all "official" documentation - Issue https://github.com/mailgun/mailgun-php/issues/387 & https://github.com/mailgun/documentation/issues/274~ (new PRs will be added soon; ignoring this point not to delay the release)
- [x] Use PSR-4 - Issue https://github.com/mailgun/mailgun-php/issues/219
- [x] Remove dependency on `php-http/message` - Issue https://github.com/mailgun/mailgun-php/issues/248 PR https://github.com/mailgun/mailgun-php/pull/428
- [x] Remove deprecated code - Issue https://github.com/mailgun/mailgun-php/issues/218
- [x] Drop PHP 5 support - Issue #475

## Other contributions

- [ ] ~Interfaces names should end with "Interface" - PR https://github.com/mailgun/mailgun-php/pull/418~
- [x] Suggest packages used on Dev - PR https://github.com/mailgun/mailgun-php/pull/440

**Comment by DavidGarciaCat** [comment]
Closing this issue due to Release 3.0.0 has been tagged:

https://github.com/mailgun/mailgun-php/releases/tag/3.0.0
